### ISSUE TITLE
Demo on Github landing page broken

### ISSUE THREAD

**Issue by rsyring** [Bahlor/jQuery-Pixel-Related-Object-Selection#1]
On the Github landing page, the code from the readme file doesn't seem to work correctly.  When i hover over the demo images, the entire image is clickable, not just the areas mentioned.

**Comment by Bahlor** [comment]
Is this problem only occuring when using the code from the readme or do you also have this problem on the demo page of the script? (http://www.cw-internetdienste.de/pixelselection/)  If you're also having the problem there... please tell me your specifications like browser, os etc. Thanks for submitting this issue!

**Comment by rsyring** [comment]
Only on the readme.

**Comment by Bahlor** [comment]
:+1: Thanks for the info, will fix it as soon as I'll be at home.
